// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oQVEiBGK_IZlXbQncSbjoF27NDg_L7g',
    appId: '1:880094830907:web:86f1e339960d4354be171e',
    messagingSenderId: '880094830907',
    projectId: 'fyp-sdd',
    authDomain: 'fyp-sdd.firebaseapp.com',
    storageBucket: 'fyp-sdd.firebasestorage.app',
    measurementId: 'G-ZQRTDM8NQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZ_XkWPCs_GJgHnmarZKUasXfFG9ea5o',
    appId: '1:880094830907:android:82beb36b5920f80abe171e',
    messagingSenderId: '880094830907',
    projectId: 'fyp-sdd',
    storageBucket: 'fyp-sdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWnUA3UkYa33jVDSy_Aq4oIYTfJCW9cgw',
    appId: '1:880094830907:ios:8a658a98259e6f09be171e',
    messagingSenderId: '880094830907',
    projectId: 'fyp-sdd',
    storageBucket: 'fyp-sdd.firebasestorage.app',
    iosBundleId: 'com.app.sdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWnUA3UkYa33jVDSy_Aq4oIYTfJCW9cgw',
    appId: '1:880094830907:ios:8cc71a2acc781586be171e',
    messagingSenderId: '880094830907',
    projectId: 'fyp-sdd',
    storageBucket: 'fyp-sdd.firebasestorage.app',
    iosBundleId: 'com.example.skinDiseaseDetectorApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5oQVEiBGK_IZlXbQncSbjoF27NDg_L7g',
    appId: '1:880094830907:web:622dbac9e7464712be171e',
    messagingSenderId: '880094830907',
    projectId: 'fyp-sdd',
    authDomain: 'fyp-sdd.firebaseapp.com',
    storageBucket: 'fyp-sdd.firebasestorage.app',
    measurementId: 'G-PXRYJTNZ10',
  );
}
